<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Appl\DonSagiv.Appl.DataAccess\DonSagiv.Appl.DataAccess.csproj" />
    <ProjectReference Include="..\..\Appl\DonSagiv.Appl.Standard\DonSagiv.Appl.Standard.csproj" />
    <ProjectReference Include="..\..\Domain\DonSagiv.Domain.Standard\DonSagiv.Domain.Standard.csproj" />
  </ItemGroup>

</Project>
